### PR TITLE
Sort edits by priority when outputting planned migration

### PR DESCRIPTION
**Pull request by alexfmpe**

### CODE REVIEW

**Comment by alexfmpe** [comment]
While this avoids printing migrations in a confusing order, I think I recall we later reached the conclusion the sorting should happen earlier - or maybe even convert the list to `Set` earlier on.
cc @danbornside

**Comment by cgibbard** [comment]
Does this print the changes in the order in which they actually occur?

**Comment by alexfmpe** [comment]
It should - I took the sorting from https://github.com/obsidiansystems/beam-automigrate/blob/228bf518e541e865f571ae824b8917400e924257/src/Database/Beam/AutoMigrate.hs#L2688

**Comment by cgibbard** [comment]
okay, seems good then :+1:

**Review by cgibbard — APPROVED** [review]

**Pull request merged**
